### PR TITLE
Refactor classes

### PR DESCRIPTION
**Pull request by lauraluiz**
@nkuehn I've reworked the code as I told you. Hopefully I've made some useful enhancements for you guys. Could you read the README to confirm it's better before merging?

Basically the changes are:
- Credentials for the project go into application.properties (inside project resources).
- There are only 2 jobs: basic import (default) and order import.
- I've restored some imports such as customer group, tax categories and categories.

### CODE REVIEW

**Comment by nkuehn** [comment]
Hi @lauraluiz , I think it's better if @sshibani  takes over this job to review in detail - he's already started his part of the automation (not sure where and in which branch though) and i guess there are some overlaps. 

Generally:
 * thanks for restoring some of the automation
 * a central credentials file is good, but better would be a format and naming that the node.js CLIs understand too:  https://github.com/sphereio/sphere-node-cli#credentials  It's well specified there and otherwise I have to configure it twice again. 

 I can't set Siawash him as a reviewer here - I guess because you or ops has to configure that first. 

@sshibani could you check you GitHub settings to make it easier to mention you?  We generally work in "push your brach to gitHub often and early" mode here to avoid overlapping work, can you push your status of the work so we can see what's going on?

**Comment by sshibani** [comment]
@nkuehn, not all tools are following that convention. https://github.com/sphereio/sphere-node-cli#credentials. I'm generating the different credentials files from a single location to be able to automate the complete process.

**Comment by nkuehn** [comment]
@sshibani  yes, but all tools are being migrated piece-by-piece into the sphere-node-cli  commandline, so for me that is the reference for the future.     And e.g. the category sync is build on the "sphere-node-utils"  ( https://github.com/sphereio/sphere-node-utils#projectcredentialsconfig ) which uses the same convention.  

the product CSV sysc is a bit off, it's the oldest  ( https://github.com/sphereio/sphere-node-product-csv-sync/blob/master/create_config.sh#L18 ) ->  but even that format is still supported by both the utils and the CLI package, so that's your lowest common denominator that should work. 

It's not all random :-)

**Comment by lauraluiz** [comment]
@nkuehn the credentials in JSON as you propose it's not a simple feature to be included in this PR. As it's not a key-value structure they use, I cannot simply tell Spring to read from it, so I suggest to create a different issue to resolve this.

I'm going to proceed to merge to master, please check the documentation for the next import. I'm going to proceed with a complete import on my side to test it. If you detect something is wrong, remember you can always use the application from its previous commit.

**Comment by nkuehn** [comment]
@lauraluiz  that's a valid point, the non-JSON format would need a custom parser.

**Pull request merged**
