### PR TITLE
Specify in README node v10 version not supported

### PR DESCRIPTION
**Pull request by lauraluiz**
With Node@10 products were never imported, among other errors. When I downgraded node to v8 it worked fine.
I've put in the readme that version ^8.2.1 is supported to be more specific, but we can also be even more specific if we know the particular versions that are supported, so feel free to modify it.

### CODE REVIEW

**Comment by lauraluiz** [comment]
Shouldn't it be this config in the package.json instead: https://docs.npmjs.com/files/package.json#engines ?

**Comment by nkuehn** [comment]
If you want to be nice to users put both.  "engines" can warn, change the dependency version selection and optionally fail hard on install.     .nvmrc  would automatically run the right version of node if you have multiple installed.

**Comment by nkuehn** [comment]
I just had the pleasure to test it all in detail due to a support issue.   It's just node 10 that does not work with the product csv sync's dependencies.  8 and 9 work. 
I wired it to 8 but documented 8 and 9 now.

**Comment by jimmythomson** [comment]
The `nconf` package version 0.11.3 and uses the `yargs` package version `^16.1.1`. When I just ran `npm install`, it installs version `16.2.0` of `yargs` due to the caret. Version 16.2.0 of yargs has a requirement of version 10 of node, and so it's currently broken when using node 8. I switched to node 14 and all looks good so far, but thought I'd mention it as I'm using `fnm` and naturally adopted the node version in `.nvmrc`, which didn't work.

**Pull request merged**
