### PR TITLE
Run tests

### PR DESCRIPTION
**Pull request by schleichardt**

### CODE REVIEW

**Comment by schleichardt** [comment]
@lauraluiz please review

**Comment by lauraluiz** [comment]
Nice! So with this we are able to start right from where we had the error, correct?

**Comment by schleichardt** [comment]
I don't get the question.

**Comment by lauraluiz** [comment]
So basically I wonder what this PR does, because the title says "Run tests" but in the implementation I see a mechanism that allows to start the inventory import from the last modified entry, so it can help recover when there was an error. Maybe the title/description could help to understand what is the issue to be reviewed?

**Comment by schleichardt** [comment]
The pull requests runs `mvn test` in travis and fixes failing tests.

**Comment by lauraluiz** [comment]
Then why is the last inventory entry useful for? Does it not affect in any way to what happens after the inventory import fails?

**Comment by schleichardt** [comment]
it is Cristians stub for a new test, he could not run it and develop further

**Pull request merged**
